<%
	'browse.asp
	Const langOldBrowser = "Your browser doesn't support this method. Copy the database path manually"
	Const langBrowse = "Browse for database"
	Const langOnlyMDB = "Only files with .MDB extention will be shown here"
	Const langDriveSelector = "Drive selector"
	Const langCannotAccessFolder = "Cannot access the folder. You probably has no rights to view it. Error: "
	Const langCurrentPath = "Current path:"
	Const langRemovable = "Removable"
	Const langFixed = "Fixed"
	Const langNetwork = "Network"
	Const langUnknown = "Unknown"
	
	'data.asp
	Const langDataForTable = "Data for table:"
	Const langAddRecord = "Add new record"
	Const langRefreshTable = "Refresh table"
	Const langXMLExport = "XML Export"
	Const langXMLExportAlt = "Export table content as XML file"
	Const langExcelExport = "Excel Export"
	Const langExcelExportAlt = "Export as delimited text file"
	Const langNoPrimaryKey = "You cannot add/update data in this table. Please set the primary key first"
	Const langEditRecord = "Edit the record"
	Const langDeleteRecord = "Delete the record"
	Const langBinaryData = "Binary data"
	Const langSureToDeleteRecord = "Are you sure you want to delete record with Primary Key(s)"
	Const langPageSize = "Page size"

	'database.asp
	Const langCouldnotSaveConfig = "Couldn't save configuration file:"
	Const langDatabaseNotExists = "Database doesn't exist"
	Const langDatabaseSelection = "Database selection"
	Const langEnterPath = "Enter a path to database or click Browse to choose it from your drive"
	Const langCurrentDatabase = "Current database is:"
	Const langOtherDatabase = "Other database"
	Const langCreateNew = "Create new"
	Const langCreateNewAlt = "(check if you want to create a blank database with path specified)"
	Const langRemovePath = "Remove this path from list"
	Const langDatabaseCompacted = "Database compacted and repaired successfully"
	Const langBackupCreated = "Backup file was created successfully"
	Const langBackupRestored = "Database was restored from backup copy"
	Const langDatabaseOptions = "Database options"
	Const langAffectCurrent = "These options will affect current database"
	Const langCompactRepair = "Compact and Repair database"
	Const langCompactRepairAlt = "Compacts and repairs (if needed) an Access 2000 database. If you perform this action on Access 97 database file, it will be converted to Access 2000."
	Const langCompactRepair97 = "Compact and Repair Access 97 database"
	Const langCompactRepair97Alt = "Compacts and repairs Access 97 database. Use this option if you don't want to upgrade your database to Access 2000"
	Const langMakeBackup = "Make backup copy of database"
	Const langMakeBackupAlt = "Creates a backup copy of your database with same file name and extention "".bak"". Any previous backups will be overwritten"
	Const langRestoreBackup = "Restore from backup"
	Const langRestoreBackupAlt = "If backup file was created before, performing this action will restore your database from backup copy. The database will be <font color=""red"" style=""color:red"">overwritten</font>!"
	Const langDatabasePassword = "Database password"

	'common
	Const langDatabaseAdministration = "Database Administration"
	Const langPrev = "Prev"
	Const langNext = "Next"
	Const langSortAscending = "Sort Ascending"
	Const langSortDescending = "Sort Descending"
	Const langSubmit = "Submit"
	
	'export_csv.asp
	Const langPleaseDefineExp = "Please define the column and rows delimiters, or use default and click Export"
	Const langTab = "Tab"
	Const langSpace = "Space"
	Const langOther = "Other"
	Const langColumnDelimiter = "Column Delimiter"
	Const langTextQualifier = "Text qualifier"
	Const langNoFieldNames = "No field names"
	
	'ftquery.asp
	Const langFreeTypeQuery = "Free-type query"
	Const langFreeTypeQueryAlt = "Free-type query allows you to make your own SQL statement and get results from it (if there are any results returned)"
	Const langTotalRecords = "Total records returned:"
	Const langTypeSQL = "Type your SQL statement in a box below."
	Const langRunIt = "Run It"
	
	'inc_nav.asp
	Const langDatabase = "Database"
	Const langTablesList = "Tables List"
	Const langProcedures = "Procedures"
	Const langViews = "Views"
	Const langRelations = "Relationships"
	Const langVisitStpWorks = "Visit StP Works web site!"
	Const langStPWorks = "StP Works"
	Const langVisitDBAdmin = "Visit Database Administrator Homepage!"
	Const langCheckUpdate = "Check for update"
	
	'main.asp
	Const langWelcomeNote = "Welcome to StP Database Administrator for web-based remote administration of your MS Access databases.<br> Please enter your administrator password and click Login<br> If this is a first time you installed StP DBAdmin, make sure to change the default password to your own."
	Const langEnterPassword = "Enter administrator password:"
	Const langPasswordsMismatch = "Passwords mismatch"
	Const langLoggedIn = "You are logged into Database administration<BR>In case you want to change the password, please type it in below"
	Const langNewPassword = "New password"
	Const langRetypeNewPassword = "Re-type new password"
	Const langChangePassword = "Change password"
	
	'qlist.asp
	Const langEnterQParams = "Please enter the parameters of procedure divided by commas. Remember to enclose text parameters in single quotation marks."
	Const langStoredProceduresList = "Stored Procedures (Queries) List"
	Const langSPName = "Name"
	Const langSPCode = "Code"
	Const langSPActions = "Actions"
	Const langCreateProcedure = "Create a new procedure"
	Const langCreateProcedureNote = "Note, if you won't add any parameter in your SQL statement, then a new View will be created instead"
	Const langProcedureName = "Procedure name:"
	Const langSQLStatement = "SQL Statement"
	Const langParams1stWay = "Parameters can be defined in 2 ways. First way, add PARAMETERS clause in your SQL statement with all parameters and thier types listed. For example:"
	Const langParams2ndWay = "The second way, when parameters determined on-the-fly. If you will add a parameter that is not recognized as a column name or SQL reserved word, it will be threated as parameter."
	Const langDeleteProcedurePrompt = "Are you sure you want to delete a stored procedure"
	
	'recedit.asp
	Const langRecord = "record"
	Const langAutoNumberNote = "Note that AutoNumber fields you cannot edit as they are updated automatically. Also columns of type Binary won't be shown here"
	Const langRecEditNote = "You can cycle through records using Update+Next/Update+Prev and Add+Next buttons. To add/update the record and return to table, click Add/Update button"
	Const langUpdate = "Update"
	Const langAdd = "Add"
	Const langReset = "Restore"
	Const langCancel = "Cancel"
	Const langRecordUpdated = "Record added/updated successfully"
	Const langFirst = "First"
	Const langLast = "Last"
	
	'relations.asp
	Const langRelationsNote = "Each of relationships described also in more readable form.<br>Note that only relationships that have any meaning are displayed"
	Const langPrimaryIndex = "Primary Index"
	Const langPrimaryTable = "Primary Table"
	Const langPrimaryColumn = "Primary Column"
	Const langForeignIndex = "Foreign Index"
	Const langForeignTable = "Foreign Table"
	Const langForeignColumn = "Foreign Column"
	Const langDeleteRelationship = "Delete this relationship"
	Const langIfFieldChanged = "If field <b><i>$PK_COLUMN_NAME</i></b> changed in <b><i>$PK_TABLE_NAME</i></b>, then field <b><i>$FK_COLUMN_NAME</i></b> in <b><i>$FK_TABLE_NAME</i></b> will be "
	Const langIfFieldDeleted = "If record with <b><i>$PK_COLUMN_NAME</i></b> deleted from <b><i>$PK_TABLE_NAME</i></b>, then all records with same <b><i>$FK_COLUMN_NAME</i></b> in <b><i>$FK_TABLE_NAME</i></b> "
	Const langChangedAlso = "changed also."
	Const langSetToNull = "set to null."
	Const langSetToDefault = "set to default value."
	Const langWillBeDeleted = "will be deleted."
	Const langCreateRelationship = "Create new relationship"
	Const langForeignIndexName = "Foreign index name"
	Const langOnUpdate = "On update:&nbsp;"
	Const langNoAction = "No Action"
	Const langSetToNull2 = "Set to Null"
	Const langOnDelete = "On delete:&nbsp;"
	Const langDelete = "Delete"
	
	'structure.asp
	Const langTableIndexes = "Table's Indexes"
	Const langShowHideIndexes = "Show/Hide Indexes"
	Const langIndexName = "Index Name"
	Const langColumn = "Column"
	Const langUnique = "Unique"
	Const langAction = "Actions"
	Const langPrimaryColumnAlt = "Primary Key column"
	Const langUniqueIndexAlt = "The index is unique"
	Const langDeleteIndexAlt = "Delete the index"
	Const langCreateIndex = "Create index"
	Const langTableStructure = "Table structure for table:&nbsp;"
	Const langOrdinal = "Ordinal"
	Const langName = "Name"
	Const langDataType = "Data type"
	Const langNullable = "Nullable"
	Const langMaxLength = "Max. length"
	Const langDefaultValue2 = "Default Value"
	Const langDescription = "Description"
	Const langEditField = "Edit the field"
	Const langRemovePK = "Remove Primary Key"
	Const langSetAsPK = "Set as Primary Key"
	Const langDeleteField = "Delete the field"
	Const langAddNewColumn = "Add new column"
	Const langCreateTableQuery = "CREATE TABLE query for this table"
	Const langCreateTableQueryAlt = "Table definition is separated from its indexes<BR>Also foreign keys have to be created separately"
	Const langAreYouSureToDelete = "Are you sure you want to delete column $name and all indexes to it?"
	
	'tablelist.asp
	Const langTableName = "Table name"
	Const langViewTableStructure = "Structure"
	Const langViewTableStructureAlt = "View table's structure"
	Const langViewTableData = "Data"
	Const langViewTableDataAlt = "View table's data"
	Const langDeleteTable = "Delete"
	Const langDeleteTableAlt = "Delete the table"
	Const langSureToDeleteTable = "Are you sure you want to delete table $table_name?"
	Const langCreateNewTable = "Create new table"
	Const langNewTableName = "New table name:&nbsp;"
	Const langTableNavigate = "Data Form"
	Const langTableNavigateAlt = "Cycle through records in table"
	
	'vlist.asp
	Const langViewsList = "Views List"
	Const langCode = "Code"
	Const langRunViewAlt = "Run view"
	Const langDeleteViewAlt = "Delete view"
	Const langCreateNewView = "Create a new view"
	Const langViewName = "View name:"
	Const langSureToDeleteView = "Are you sure you want to delete view $name?"
%>