<%
	'browse.asp
	Const langOldBrowser = "Ваш броузер не поддерживает данный метод. Вам нужно скопировать путь в ручную."
	Const langBrowse = "Поиск базы данных"
	Const langOnlyMDB = "Только файлы с расширением MDB будут отображены здесь"
	Const langDriveSelector = "Выбор диска"
	Const langCannotAccessFolder = "Нет доступа к папке. Ошибка: "
	Const langCurrentPath = "Текущий путь"
	Const langRemovable = "Съемный диск"
	Const langFixed = "Жесткий диск"
	Const langNetwork = "Сеть"
	Const langUnknown = "Неизвестный"
	
	'data.asp
	Const langDataForTable = "Данные для таблицы:"
	Const langAddRecord = "Добавить новую запись"
	Const langRefreshTable = "Освежить данные"
	Const langXMLExport = "Экспорт в XML"
	Const langXMLExportAlt = "Экспортировать данные в XML формате"
	Const langExcelExport = "Экспорт для Excel"
	Const langExcelExportAlt = "Экпортировать данные для Excel"
	Const langNoPrimaryKey = "Вы не можете изменить данные в этой таблице. Ключевое поле не установлено"
	Const langEditRecord = "Редактировать запись"
	Const langDeleteRecord = "Удалить запись"
	Const langBinaryData = "Бинарное поле"
	Const langSureToDeleteRecord = "Вы уверены что хотите удалить запись с ключом (ключами)"
	Const langPageSize = "Размер страницы"

	'database.asp
	Const langCouldnotSaveConfig = "Не удалось сохранить файл конфигурации:"
	Const langDatabaseNotExists = "Выбранная база данных не существует"
	Const langDatabaseSelection = "Выбор базы данных"
	Const langEnterPath = "Введите путь к базе данных или нажмите на кнопку слева для поиска"
	Const langCurrentDatabase = "Текущая база данных:"
	Const langOtherDatabase = "Другая"
	Const langCreateNew = "Создать новую"
	Const langCreateNewAlt = "(выделите если Вы хотите создать новую базу данных с набранным путем)"
	Const langRemovePath = "Удалить из списка"
	Const langDatabaseCompacted = "База данных исправлена и сжата удачно"
	Const langBackupCreated = "Запасая база данных создана удачно"
	Const langBackupRestored = "База данных востановлена с запасной копии"
	Const langDatabaseOptions = "Опции базы данных"
	Const langAffectCurrent = "Эти опции работают с текужей базой данных"
	Const langCompactRepair = "Сжать и исправить базу данных"
	Const langCompactRepairAlt = "Сжимает и исправляет (если есть необходимость) базу данных Access 2000. Если провести эту операцию над базой данных Access 97 , то она будет конвертирована в Access 2000."
	Const langCompactRepair97 = "Сжать и исправить базу данных Access 97"
	Const langCompactRepair97Alt = "Сжимает и исправляет (если есть необходимость) базу данных Access 97. Используйте эту операцию если вы не хотите конвертировать Вашу базу данных в Access 2000"
	Const langMakeBackup = "Make backup copy of database"
	Const langMakeBackupAlt = "Создает копию базы данных с тем же именем и расширением "".bak"". Любая предыдущая копия будет перезаписана"
	Const langRestoreBackup = "Восстановить из копии"
	Const langRestoreBackupAlt = "Если копия базы данных была создана ранее, эта операция восстановит (заменит) текущую базу данных из копии. Текущая база данных будет <font color=""red"" style=""color:red"">перезаписана</font>!"
	Const langDatabasePassword = "Пароль базы данных"

	'common
	Const langDatabaseAdministration = "Администрирование базы данных"
	Const langPrev = "Пред."
	Const langNext = "Посл."
	Const langSortAscending = "Сортировать по возрастающей"
	Const langSortDescending = "Сортировать по убывающей"
	Const langSubmit = "Подтвердить"
	
	'export_csv.asp
	Const langPleaseDefineExp = "Пожалуйста, установите разделители или используйте ваделенные и нажмите Экспорт"
	Const langTab = "Tab"
	Const langSpace = "Пробел"
	Const langOther = "Другое"
	Const langColumnDelimiter = "Разделитель полей"
	Const langTextQualifier = "Определитель текста"
	Const langNoFieldNames = "Без названий полей"
	
	'ftquery.asp
	Const langFreeTypeQuery = "SQL запрос"
	Const langFreeTypeQueryAlt = "SQL запрос позволяет выполнить любой SQL скрипт и просвотреть резальты (если таковые имеются)"
	Const langTotalRecords = "Всего записей возвращено:"
	Const langTypeSQL = "Наберите SQL запрос. Вы можете ввести несколько запросов, разделяя их точкой с запятой (;)"	'updated in version 1.8
	Const langRunIt = "Выполнить"
	Const langUseTransaction = "Исполнить в одной транзакции"		'new in version 1.8
	Const langIgnoreErrors = "Игнорировать ошибки"					'new in version 1.8
	
	'inc_nav.asp
	Const langDatabase = "База данных"
	Const langTablesList = "Таблицы"
	Const langProcedures = "Процедуры"
	Const langViews = "Виды"
	Const langRelations = "Отношения"
	Const langVisitStpWorks = "Посетите сайт StPWorks!"
	Const langStPWorks = "StP Works"
	Const langVisitDBAdmin = "Страница Администратора"
	Const langCheckUpdate = "Проверить новую версию"
	
	'main.asp
	Const langWelcomeNote = "Добро пожаловать в StP Database Administrator - удаленное администрирование баз данных через Интернет.<br> Пожалуйста введите пароль администратора<br> Если это первый раз после установки программы, не забудьте сменить пароль."
	Const langEnterPassword = "Введите пароль:"
	Const langPasswordsMismatch = "Пароли не совпадают"
	Const langLoggedIn = "Вы успешно вошли в систему<BR>Если вы хотите изменить пароль, наберите новый пароль ниже"
	Const langNewPassword = "Новый пароль"
	Const langRetypeNewPassword = "Подтвердите новый пароль"
	Const langChangePassword = "Изменить пароль"
	
	'qlist.asp
	Const langEnterQParams = "Пожалуйста введите параметры процедуры разделяя их запятыми. Не забудьте поставить кавычки вокруг текстовых параметров."
	Const langStoredProceduresList = "Список процедур"
	Const langSPName = "Название"
	Const langSPCode = "Скрипт"
	Const langSPActions = "Действия"
	Const langCreateProcedure = "Создать процедуру"
	Const langCreateProcedureNote = "Если ни одного параметра не будет указано, то новый Вид будет создан вместо процедуры"
	Const langProcedureName = "Название процедуры:"
	Const langSQLStatement = "SQL скрипт"
	Const langParams1stWay = "Параметры могут быть определены двумя способами. Первый способ - добавьте раздел PARAMETERS в SQL коде со всеми параметрами и их типами. Например:"
	Const langParams2ndWay = "Второй способ - когда параметры определяются во время выполнения. Если вы введете какой-либо текст который не будет распознан как таблица, поле или зарезервированное слово, то он будет считаться внешним параметром."
	Const langDeleteProcedurePrompt = "Вы уверены что хотите удалить процедуру"
	
	'recedit.asp
	Const langRecord = "запись"
	Const langAutoNumberNote = "Поля AutoNumber не могут быть изменены так как они заполняются автоматически. Также поля бинарного типа не поддерживаются"
	Const langRecEditNote = "Вы можете передвигаться к следующей/предыдущей записи не возвращаясь в таблицу."
	Const langUpdate = "Изменить"
	Const langAdd = "Добавить"
	Const langReset = "Восстановить"
	Const langCancel = "Отмена"
	Const langRecordUpdated = "Запись изменена/добавлена успешно"
	Const langFirst = "Первая"
	Const langLast = "Последняя"
	
	'relations.asp
	Const langRelationsNote = "Отношения между таблицами описаны в более читабельной форме.<br>Только отношения которые имеют хоть какое-либо значение будут отображены."
	Const langPrimaryIndex = "Основной индекс"
	Const langPrimaryTable = "Основная таблица"
	Const langPrimaryColumn = "Основное поле"
	Const langForeignIndex = "Второстепенный индекс"
	Const langForeignTable = "Второстепенная таблица"
	Const langForeignColumn = "Второстепенное поле"
	Const langDeleteRelationship = "Удалить"
	Const langIfFieldChanged = "Усли поле <b><i>$PK_COLUMN_NAME</i></b> изменено в <b><i>$PK_TABLE_NAME</i></b>, тогда поле <b><i>$FK_COLUMN_NAME</i></b> в <b><i>$FK_TABLE_NAME</i></b> будет "
	Const langIfFieldDeleted = "Если запись с <b><i>$PK_COLUMN_NAME</i></b> будет удалена из <b><i>$PK_TABLE_NAME</i></b>, тогда все записи с таким значением в <b><i>$FK_COLUMN_NAME</i></b> в <b><i>$FK_TABLE_NAME</i></b> "
	Const langChangedAlso = "также изменено."
	Const langSetToNull = "изменено на null."
	Const langSetToDefault = "установлено в стандартное значение."
	Const langWillBeDeleted = "удалена."
	Const langCreateRelationship = "Создать отношение"
	Const langForeignIndexName = "Название индекса"
	Const langOnUpdate = "При изменении:&nbsp;"
	Const langNoAction = "Без изменений"
	Const langSetToNull2 = "Установить в Null"
	Const langOnDelete = "При удалении:&nbsp;"
	Const langDelete = "Удалить"
	
	'structure.asp
	Const langTableIndexes = "Индексы в таблице"
	Const langShowHideIndexes = "Показать/спрятать индекы"
	Const langIndexName = "Название индекса"
	Const langColumn = "Поле"
	Const langUnique = "Уникальное"
	Const langAction = "Действия"
	Const langPrimaryColumnAlt = "Ключевое поле"
	Const langUniqueIndexAlt = "Индекс уникален"
	Const langDeleteIndexAlt = "Удалить индекс"
	Const langCreateIndex = "Создать индекс"
	Const langTableStructure = "Структура таблицы:&nbsp;"
	Const langOrdinal = "Порядковый номер"
	Const langName = "Название"
	Const langDataType = "Тип данных"
	Const langNullable = "Нулевое"
	Const langMaxLength = "Макс. длина"
	Const langDefaultValue2 = "Стандартное значение"
	Const langDescription = "Описание"
	Const langEditField = "Редактировать поле"
	Const langRemovePK = "Удалить ключ"
	Const langSetAsPK = "Установить как ключевое"
	Const langDeleteField = "Удалить поле"
	Const langAddNewColumn = "Добавить поле"
	Const langCreateTableQuery = "Скрипт создания страницы"
	Const langCreateTableQueryAlt = "Определение таблицы отделено от индексов<BR>Внешние индексы должны быть созданы отдельно"
	Const langAreYouSureToDelete = "Вы уверены что хотите удалить поле $name и все его индексы?"
	
	'tablelist.asp
	Const langTableName = "Название таблицы"
	Const langViewTableStructure = "Структура"
	Const langViewTableStructureAlt = "Просмотреть/изменить структуру таблицы"
	Const langViewTableData = "Данные"
	Const langViewTableDataAlt = "Просмотреть/изменить данные в таблице"
	Const langDeleteTable = "Удалить"
	Const langDeleteTableAlt = "Удалить таблицу"
	Const langSureToDeleteTable = "Вы уверены что хотите удалить таблицу $table_name?"
	Const langCreateNewTable = "Создать таблицу"
	Const langNewTableName = "Название таблицы:&nbsp;"
	Const langTableNavigate = "Пробег"
	Const langTableNavigateAlt = "Быстрый просмотр записей в таблице и/или изменение"
	
	'vlist.asp
	Const langViewsList = "Список видов"
	Const langCode = "Скрипт"
	Const langRunViewAlt = "Исполнить"
	Const langDeleteViewAlt = "Удалить вид"
	Const langCreateNewView = "Создать новый"
	Const langViewName = "Название:"
	Const langSureToDeleteView = "Вы уверены что хотите удалить вид $name?"
%>