<!--BEGIN FOOTER -->
<div align="center" style="margin-top: 40px">
	<a href="http://www.stpworks.com" target="_blank"><img src="images/DBAdmin_logo.gif" width="98" height="32" border="0" alt="StpWorks Database Administrator"></a><br>
	<i><font size="1">Powered by <a href="http://www.stpworks.com" target="_blank">StpWorks.com</a></font></i>
</div>
<!-- END FOOTER -->
<%
	'Free configuration object
	if not IsEmpty(StpProfile) then set StpProfile = Nothing
%>