<%
	'Header of language file
	'#language=English
	'#product=Stp Database Administrator
	'#created=2002-8-7
	'#modified=2002-13-12
	'#author=Philip Patrick
	'#email=stpatrick@mail.com
	'#web=http://www.stpworks.com
	'#comment=Use this file as a template for your own language
	
	'browse.asp
	Const langOldBrowser = "Your browser doesn't support this method. Copy the database path manually"
	Const langBrowse = "Browse for database"
	Const langOnlyMDB = "Only files with .MDB extention will be shown here"
	Const langDriveSelector = "Drive selector"
	Const langCannotAccessFolder = "Cannot access the folder. You probably have no rights to view it. Error: "
	Const langCurrentPath = "Current path:"
	Const langRemovable = "Removable"
	Const langFixed = "Fixed"
	Const langNetwork = "Network"
	Const langUnknown = "Unknown"

	'common
	Const langPrev = "Prev"
	Const langNext = "Next"
	Const langSortAscending = "Sort Ascending"
	Const langSortDescending = "Sort Descending"
	Const langSubmit = "Submit"
	Const langReset = "Restore"
	Const langNo = "No"
	Const langYes = "Yes"
	Const langCopyToClipboard = "Copy to clipboard"
	Const langCancel = "Cancel"
	Const langTablesList = "Tables"
	
	'data.asp
	Const langDataForTable = "&nbsp;:&nbsp;Data"
	Const langAddRecord = "Add new record"
	Const langRefreshTable = "Refresh table"
	Const langXMLExport = "XML Export"
	Const langXMLExportAlt = "Export table content as XML file"
	Const langExcelExport = "Excel Export"
	Const langExcelExportAlt = "Export as delimited text file"
	Const langNoPrimaryKey = "You cannot add/update data in this table. Please set the primary key first"
	Const langEditRecord = "Edit the record"
	Const langDeleteRecord = "Delete the record"
	Const langBinaryData = "Binary data"
	Const langSureToDeleteRecord = "Are you sure you want to delete record with Primary Key(s)"
	Const langPageSize = "Page size"

	'database.asp
	Const langDatabaseSelection = "Database Select"
	Const langDatabaseSelectionAlt= "Please select a database to work"
	Const langEnterPath = "To start working, select a database using Browse button or from the list below. You can also create a new blank database by typing a name of non-existent file and selecting ""Create blank"" checkbox"
	Const langCurrentDatabase = "Database:"
	Const langCreateNew = "Create blank database"
	Const langCreateNewAlt = "(check if you want to create a blank database with path specified)"
	Const langDatabaseCompacted = "Database compacted and repaired successfully"
	Const langBackupCreated = "Backup file was created successfully"
	Const langBackupRestored = "Database was restored from backup copy"
	Const langDatabaseOptions = "Database options"
	Const langAffectCurrent = "These actions will affect the current database"
	Const langCompactRepair = "Compact and Repair database"
	Const langCompactRepairAlt = "Compacts and repairs (if needed) an MS Access database."
	Const langConvert2000 = "Convert to Access 2000"
	Const langConvert2000Alt = "Converts Access 97 database to Access 2000, then compacts and repairs it."
	Const langMakeBackup = "Make backup copy of database"
	Const langMakeBackupAlt = "Creates a backup copy of your database with same file name and extention '.bak'. Any previous backups will be overwritten"
	Const langRestoreBackup = "Restore from backup"
	Const langRestoreBackupAlt = "If backup file was created before, performing this action will restore your database from backup copy. The database will be overwritten!"
	Const langDatabasePassword = "Database password:"
	Const langDatabasePath = "Path:"
	Const langNewDatabasePassword = "Set database password"
	Const langNewDatabasePasswordAlt = "Set a new database password or leave blank to remove the current one"
	Const langNewPasswordSet = "Database password has been changed successfully"
	Const langRemoveDBPathAlt = "Remove database's path from list"
	Const langActions = "Actions"
	Const langProperties = "Properties"
	Const langFileSize = "File size:"
	Const langSizeAfterCompact = "Size after compact:"
	Const langNewPassword = "New password"
	Const langRetypeNewPassword = "Re-type password"
	Const langChangePassword = "Change password"
	Const langPasswordsMismatch = "Passwords mismatch"
	
	'default.asp
	Const langWelcome = "Welcome"
	Const langWelcomeHeader = "Welcome to Stp Database Administrator"
	Const langWelcomeNote = "Stp Database Administrator allows you to manage your MSAccess databases through the Web, using only your browser, from any place, at any time."
	Const langWelcomeNote2 = "To start working with your databases, type your administrator password in the text box below and click Enter."
	Const langEnterPassword = "Password:"
	Const langVersion = "Version"
	Const langSubmitBug = "Submit a bug"
	
	'export_db.asp
	Const langDatabaseExport = "Database Export"
	Const langDatabaseExportAlt = "Generate SQL script for selected tables, views and/or stored procedures"
	Const langDatabaseExportNote = "Use Shift and Ctrl to select multiple tables, views and/or stored procedures"
	Const langOptions = "Options"
	Const langIncludeRelations = "Include relations"
	Const langGenerateSQLScript = "Generate SQL script"
	Const langSQLScriptNote = "Generated SQL script for selected objects in database"
	Const langProcedures = "Procedures"
	Const langViews = "Views"
	
	'export_csv.asp
	Const langPleaseDefineExp = "Please define the column and rows delimiters, or use default and click Export"
	Const langTab = "Tab"
	Const langSpace = "Space"
	Const langOther = "Other"
	Const langColumnDelimiter = "Column Delimiter"
	Const langTextQualifier = "Text qualifier"
	Const langNoFieldNames = "No field names"
	
	'ftquery.asp
	Const langFreeTypeQuery = "Free-Type Query : Script"
	Const langFreeTypeQueryAlt = "Free-Type Query allows you to make your own SQL statement and get results from it (if there are any results returned)"
	Const langTotalRecords = "Total records returned:"
	Const langRunIt = "Execute"
	Const langTypeSQL = "Type your SQL statement in a box below. You can run several queries at once, separating each of them with semicolon (;)"	'updated in version 1.8
	Const langUseTransaction = "Run in one transaction"		'new in version 2.0
	Const langIgnoreErrors = "Ignore errors"				'new in version 2.0
	Const langFTQResults = "Free-Type Query : Results"
	Const langRecordsAffected = "Records affected:"
	
	'qlist.asp
	Const langEnterQParams = "Please enter the parameters of procedure divided by commas. Remember to enclose text parameters in single quotation marks."
	Const langStoredProceduresList = "Stored Procedures"
	Const langSPName = "Name"
	Const langSPCode = "Code"
	Const langSPActions = "Actions"
	Const langCreateProcedure = "Create a new procedure"
	Const langUpdateProcedure = "Update procedure"
	Const langCreateProcedureNote = "Note, if you won't add any parameter in your SQL statement, then a new View will be created instead"
	Const langProcedureName = "Procedure name:"
	Const langSQLStatement = "SQL Statement"
	Const langParams1stWay = "Parameters can be defined in 2 ways. First way, by adding PARAMETERS clause in your SQL statement with all parameters and thier types listed. For example:"
	Const langParams2ndWay = "The second way, when parameters are determined on-the-fly. If you will add a parameter that is not recognized as a column name or SQL reserved word, it will be threated as parameter."
	Const langDeleteProcedurePrompt = "Are you sure you want to delete a stored procedure"
	Const langSPExecute = "Execute Stored Procedure"
	Const langSPEdit = "Edit Procedure"
	Const langSPDelete = "Delete Stored Procedure"
	
	'recedit.asp
	Const langRecord = "record"
	Const langAutoNumberNote = "Note that AutoNumber fields you cannot edit as they are updated automatically. Also columns of type Binary won't be shown here"
	Const langRecEditNote = "You can cycle through records using Update+Next/Update+Prev and Add+Next buttons. To add/update the record and return to table, click Add/Update button"
	Const langUpdate = "Update"
	Const langAdd = "Add"
	Const langRecordUpdated = "Record added/updated successfully"
	Const langFirst = "First"
	Const langLast = "Last"
	
	'relations.asp
	Const langRelationsNote = "Each of relationships described also in more readable form."
	Const langPrimaryIndex = "Primary Index"
	Const langPrimaryTable = "Primary Table"
	Const langPrimaryColumn = "Primary Column"
	Const langForeignIndex = "Foreign Index"
	Const langForeignTable = "Foreign Table"
	Const langForeignColumn = "Foreign Column"
	Const langDeleteRelationship = "Delete this relationship"
	Const langIfFieldChanged = "If field <b><i>$PK_COLUMN_NAME</i></b> has been changed in <b><i>$PK_TABLE_NAME</i></b>, then field <b><i>$FK_COLUMN_NAME</i></b> in <b><i>$FK_TABLE_NAME</i></b> will be "
	Const langIfFieldDeleted = "If record with <b><i>$PK_COLUMN_NAME</i></b> has been deleted from <b><i>$PK_TABLE_NAME</i></b>, then all records with same <b><i>$FK_COLUMN_NAME</i></b> in <b><i>$FK_TABLE_NAME</i></b> "
	Const langChangedAlso = "changed also."
	Const langSetToNull = "set to null."
	Const langSetToDefault = "set to default value."
	Const langWillBeDeleted = "will be deleted."
	Const langCreateRelationship = "Create new relationship"
	Const langForeignIndexName = "Foreign index name"
	Const langOnUpdate = "On update:&nbsp;"
	Const langNoAction = "No Action"
	Const langOnDelete = "On delete:&nbsp;"
	Const langDelete = "Delete"
	Const langRelations = "Relationships"
	
	'settings.asp
	Const langSettings = "Settings"
	Const langSettingsNotAvailable = "Sorry, the Settings page is not availeble since you haven't specified an XML file path. If you wish to do it now, please open <font color=""green"">scripts/inc_config.asp</font> file in any text editor, such as Notepad and change the value of <font color=""green"">DBA_cfgProfilePath</font>"
	Const langSessionVariables = "Session Variables"
	Const langUsername = "Username"
	Const langUserPassword = "User's Password"
	Const langDBPath = "Database path"
	Const langDBPassword = "Database password"
	Const langSaveDBPaths = "Save database paths?"
	Const langOtherSettings = "Other settings"
	Const langSaveSuccess = "Settings were saved successfully"
	
	'structure.asp
	Const langTableIndexes = "&nbsp;:&nbsp;Indexes"
	Const langIndexName = "Index Name"
	Const langColumn = "Column"
	Const langUnique = "Unique"
	Const langIndexedUnique = "Yes, unique index"
	Const langIndxedDuplicates = "Yes, allow duplicates"
	Const langPrimaryColumnAlt = "Primary Key column"
	Const langUniqueIndexAlt = "The index is unique"
	Const langDeleteIndexAlt = "Delete the index"
	Const langCreateIndex = "Create index"
	Const langTableStructure = "&nbsp:&nbsp;Structure"
	Const langOrdinal = "Ordinal"
	Const langName = "Name"
	Const langDataType = "Data type"
	Const langNullable = "Nullable"
	Const langMaxLength = "Max. length"
	Const langDefaultValue2 = "Default Value"
	Const langDescription = "Description"
	Const langEditField = "Edit column"
	Const langRemovePK = "Remove Primary Key"
	Const langSetAsPK = "Set as Primary Key"
	Const langDeleteField = "Delete column"
	Const langAddNewColumn = "Add new column"
	Const langCreateTableQuery = "&nbsp;:&nbsp;SQL"
	Const langCreateTableQueryAlt = "CREATE TABLE SQL script that can be used to re-created this table"
	Const langAreYouSureToDelete = "Are you sure you want to delete column $name and all indexes to it?"
	Const langAllowZeroLength = "Allow zero-length"
	Const langUnicodeCompress = "Compress Unicode"
	Const langIndexed = "Indexed"
	
	'tablelist.asp
	Const langTableName = "Table name"
	Const langCreated = "Created"
	Const langModified = "Modified"
	Const langViewTableStructureAlt = "View table's structure"
	Const langViewTableDataAlt = "View table's data"
	Const langDeleteTableAlt = "Delete the table"
	Const langSureToDeleteTable = "Are you sure you want to delete table $table_name?"
	Const langCreateNewTable = "Create new table"
	Const langNewTableName = "New table name:&nbsp;"
	Const langTableNavigateAlt = "Cycle through records in table"
	
	'vlist.asp
	Const langRunViewAlt = "Run view"
	Const langDeleteViewAlt = "Delete view"
	Const langCreateNewView = "Create a new view"
	Const langViewName = "View name:"
	Const langSureToDeleteView = "Are you sure you want to delete view $name?"
	Const langUpdateView = "Update view"
	Const langEditView = "Edit View"
%>